

services:
  # grafana is a service that provides a web-based interface for visualizing
  # and analyzing monitoring data collected by Prometheus.
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_service
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
      - ./grafana/datasources.yml:/app/grafana/datasources/datasources.yml:ro
      - ./grafana/dashboards.yml:/app/grafana/dashboards/dashboards.yml:ro
      - ./grafana/system-metrics.json:/app/grafana/dashboards/system-metrics.json:ro
    env_file:
      - ../.env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_SERVER_HTTP_PORT=${GF_SERVER_HTTP_PORT}
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus

  # prometheus is a service that collects and stores metrics from various
  # monitored targets with alerting capabilities.
  prometheus:
    image: prom/prometheus:latest
    user: "0"
    container_name: prometheus_service
    ports:
      - "9091:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/app/prometheus/prometheus.yml:ro
      - ./prometheus/alert-rules.yml:/app/prometheus/alert-rules.yml:ro
    env_file:
      - ../.env
    command:
      - '--config.file=/app/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/app/prometheus/console_libraries'
      - '--web.console.templates=/app/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  grafana_data:
    driver: local
  grafana_logs:
    driver: local
  prometheus_data:
    driver: local

networks:
  monitoring:
    driver: bridge