
# need to create game logs

# logs located at /ops/ELK/Logstash/logs will be processed to create graphs in Kibana
# Access Kibana:        https://localhost:5601 (username: elastic, password: from .env)
# Access Elasticsearch: https://localhost:9200 (requires authentication)
# 
# Kibana dataview needs to be created:
#  https://localhost:5601/app/management/kibana/dataViews
#
# Logstash secure endpoints:
#  - TCP (TLS):   port 5069
#  - HTTP (TLS):  port 8080
#  - Beats (TLS): port 5044

services:
  # processes and ships logs
  logstash:
    build:
      context: ./Logstash
      dockerfile: Dockerfile
    container_name: ft_logstash
    env_file:
      - ../.env
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./Logstash/pipeline:/app/pipeline
      - ./Logstash/config:/app/config
      - ./Logstash/logs:/app/logs
      - ./Elasticsearch/certs:/app/config/certs:ro
    ports:
      - "5069:5069"
      - "8080:8080"
      - "5044:5044"
    networks:
      - ELK
    restart: unless-stopped

  # indexes + stores logs
  elasticsearch:
    build:
      context: ./Elasticsearch
      dockerfile: Dockerfile
    container_name: ft_elasticsearch
    env_file:
      - ../.env
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=${XPACK_MONITORING_ENABLED}
      - bootstrap.memory_lock=false 
    volumes:
      - es_data:/app/data
      - ./Elasticsearch/certs:/app/certs:ro
    ports:
      - "9200:9200"
    networks:
      - ELK
    restart: unless-stopped

  # visualizes logs as graphs
  kibana:
    build:
      context: ./Kibana
      dockerfile: Dockerfile
    container_name: ft_kibana
    env_file:
      - ../.env
    volumes:
      - ./Elasticsearch/certs:/app/certs:ro
      - kibana_data:/app/data
    ports:
      - "5601:5601"
    networks:
      - ELK
    restart: unless-stopped

  # volume for persisting Elasticsearch and Kibana data
volumes:
  es_data:
  kibana_data:

  # network for ELK stack
networks:
  ELK:
    driver: bridge
